use `customer_behavior`;
show tables;
select *from customer limit 5;
-- What is the total revenue generated by male vs. female customers?
alter table customer
change column `Purchase Amount (USD)` purchase_amount int;
 
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


-- Which customers used a discount but still spent more than the average purchase amount?
select`Customer ID`,`purchase_amount`
from customer 
where `Discount Applied` = 'yes' and `purchase_amount` >= (select avg(`purchase_amount`) from customer );



-- Which are the top 5 products with the highest average review rating?
select `Item Purchased` , avg(`Review Rating`) as "avgrating"
from customer 
group by `Item Purchased` 
order by avg(`Review Rating`) desc 
limit 5;

-- How do the average purchase amounts compare between Standard and Express shipping?

select `Shipping Type` , round(avg(`purchase_amount`),2)
from customer
where `Shipping Type` in ('Standard','Express')
group by `Shipping Type`;


-- Do subscribed customers spend more than non-subscribers? Compare average spend and total revenue.

select `Subscription Status`,
count(`Customer ID`),avg(`purchase_amount`), sum(`purchase_amount`)
from customer
group by `Subscription Status`
order by `Subscription Status` desc;

-- Which 5 products have the highest percentage of purchases with discounts applied?

select `Item Purchased` , 
round(100*sum( case when `Discount Applied` = 'Yes' then 1 else 0 end)/count(*),2) as dicount_rate
from customer
group by `Item Purchased`
order by `Item Purchased` desc
limit 5;

-- How can customers be segmented into New, Returning, and Loyal based on previous purchases, and what is the count of each segment?
WITH customer_type AS (
    SELECT
        `Customer ID`,
        `Previous Purchases`,
        CASE
            WHEN `Previous Purchases` = 1 THEN 'NEW'
            WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'RETURNING'
            ELSE 'LOYAL'
        END AS customer_segmentation
    FROM customer
)
SELECT
    customer_segmentation,
    COUNT(*) AS `number of customers`
FROM customer_type
GROUP BY customer_segmentation;




-- What are the top 3 most purchased products within each category?

-- Are repeat buyers (customers with more than 5 previous purchases) more likely to subscribe?

-- What is the revenue contribution of each age group?
